### ISSUE TITLE
for(let

### ISSUE THREAD

**Issue by L3P3** [LFF5644/minecraftServerStarter#1]
Hast du schön gemacht! :)

Aber tu mal das `let` in die `for()` rein, also `for(let ...)`!
Dass das auf uralten Node-Versionen nicht geht, ist ja egal!

**Comment by LFF5644** [comment]
ne ich nutze auf einem gerät node 8 und deswegen werde ich dies immer 
`let varName;
for(varName of x){...}`
schreiben!
